---
ID: "3c2c1ef3-f8d0-56ce-82bc-d272c7df6dcd"
Parent: "e7725985-cdc0-5db1-9fe8-e5008bbfe312"
Template: "e7725985-cdc0-5db1-9fe8-e5008bbfe312"
Path: /sitecore/templates/Project/altudoapp/ExampleCustomRouteType/__Standard Values
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220225T122122Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
