---
ID: "6e943f36-7928-5113-975a-afe600139d66"
Parent: "793ffd10-5364-57f3-a0cb-4f892ea6262d"
Template: "793ffd10-5364-57f3-a0cb-4f892ea6262d"
Path: "/sitecore/templates/Project/cts/Styleguide-FieldUsage-Image/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220225T044639Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
