---
ID: "ad3def68-fbd8-4503-b62c-0bdbfa4f7605"
Parent: "65cca095-5f6d-49fc-a59f-c6c4708822dc"
Template: "65cca095-5f6d-49fc-a59f-c6c4708822dc"
Path: /sitecore/templates/Project/Test Tenant/Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220321T172431Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
