---
ID: "42e1fa85-39e7-535a-ab33-429dfaf04481"
Parent: "e604fd21-faee-56c8-95b1-e2a149d02fb4"
Template: "e604fd21-faee-56c8-95b1-e2a149d02fb4"
Path: "/sitecore/templates/Project/altudoapp/Styleguide-FieldUsage-Image/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220225T122126Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
