---
ID: "ccdcea25-7fd8-4760-aebe-ca6970974255"
Parent: "65bcf034-2c16-44d2-bf0b-f546b6585c02"
Template: "65bcf034-2c16-44d2-bf0b-f546b6585c02"
Path: /sitecore/templates/Project/molina/PageNotFound/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{BDBA83F0-14B4-5150-9922-3A015EE0BEC3}">
        <r
          id="{255A6531-08AA-40E7-BA61-4FF04EDBAA32}"
          ph="jss-main"
          uid="{F4F6F922-8BE8-4B32-B83A-4F0ED95047E5}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220301T035443Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
