---
ID: "bd73a449-b6f3-48ac-8875-c96658a14cac"
Parent: "3e3950cd-411c-4a75-b665-37b8e2c0bf19"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Altudo/MolinaSXA/Presentation/Rendering Variants/Search Results/Product Vertical
DB: master
SharedFields:
- ID: "e1d5adba-8348-4127-9bb6-455936653839"
  Hint: CssClass
  Value: vertical
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220321T043453Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
