---
ID: "00d11786-dffb-42b7-8f25-645803f92c81"
Parent: "3d048504-d5c0-462a-8f73-7bae5de44c17"
Template: "3d048504-d5c0-462a-8f73-7bae5de44c17"
Path: /sitecore/templates/Project/Test Tenant/Tenant/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220321T172430Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
