---
ID: "46b36cf1-e9b9-49e6-83be-9670985681de"
Parent: "ff51bf41-a501-4b28-afe5-674a823b1403"
Template: "fcd285da-9ab2-4c8d-b185-5a7487a9ba1b"
Path: /sitecore/content/Altudo/MolinaSXA/Presentation/Rendering Variants/Page Content/Product Variant/ProductId
DB: master
SharedFields:
- ID: "4753764c-c05a-4623-841b-97f85135241c"
  Hint: FieldName
  Value: ProductId
- ID: "db805bdc-8eec-4238-b174-2427b6f1f077"
  Hint: Tag
  Value: "{7FF0B09B-8AAA-469B-8A56-4743E61705EC}"
- ID: "fe56eae5-d6a1-4703-92f7-4862da6deac8"
  Hint: RenderIfEmpty
  Type: Checkbox
  Value: 0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220317T063319Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
