---
ID: "ba7fa6cc-b76f-4da6-af64-31f9c85fb742"
Parent: "ff51bf41-a501-4b28-afe5-674a823b1403"
Template: "070a64fa-5f1b-40cc-83cb-3ce05d1895fc"
Path: /sitecore/content/Altudo/MolinaSXA/Presentation/Rendering Variants/Page Content/Product Variant/ProductImage
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
- ID: "df178dc4-b83d-46ec-8d4f-9de85e2c996c"
  Hint: FieldName
  Value: ProductImage
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220317T063438Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
