---
ID: "3fa57d27-64e5-4fb0-b82e-b1914952b201"
Parent: "ff51bf41-a501-4b28-afe5-674a823b1403"
Template: "fcd285da-9ab2-4c8d-b185-5a7487a9ba1b"
Path: /sitecore/content/Altudo/MolinaSXA/Presentation/Rendering Variants/Page Content/Product Variant/ProductSpecification
DB: master
SharedFields:
- ID: "4753764c-c05a-4623-841b-97f85135241c"
  Hint: FieldName
  Value: ProductSpecification
- ID: "fe56eae5-d6a1-4703-92f7-4862da6deac8"
  Hint: RenderIfEmpty
  Type: Checkbox
  Value: 0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220317T063526Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
