---
ID: "5290acdc-21b4-5b3e-8f08-2a2eceff2c34"
Parent: "7cd5d07d-653b-5a79-b1b4-8a7e7ecfb0ac"
Template: "7cd5d07d-653b-5a79-b1b4-8a7e7ecfb0ac"
Path: "/sitecore/templates/Project/altudoapp/Styleguide-RouteFields/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220225T122128Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
