---
ID: "1538cadb-38ae-4db5-95c6-cf4733319c7e"
Parent: "a03db2da-c90c-468c-9b87-354e2526c4e4"
Template: "53cf4e9b-9684-4e82-8b9d-5b25db81f30e"
Path: /sitecore/content/Altudo/MolinaSXA/Presentation/Partial Designs/Product Partial
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220317T063811Z
