---
ID: "a52a352f-c81f-4460-b7bd-2cb6b3578ef8"
Parent: "a9172afa-c97f-4b76-8e16-9a8a4b5d71de"
Template: "a9172afa-c97f-4b76-8e16-9a8a4b5d71de"
Path: /sitecore/templates/Project/Altudo/Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220317T033206Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
