---
ID: "ff51bf41-a501-4b28-afe5-674a823b1403"
Parent: "4dcca98d-d3fb-43d8-ada5-e5b3377522a9"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Altudo/MolinaSXA/Presentation/Rendering Variants/Page Content/Product Variant
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220317T063229Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
