---
ID: "260aa6a7-3a79-5453-ad45-d959906f9429"
Parent: "402820d0-f9b3-5bbe-b5e2-52e8198270a2"
Template: "402820d0-f9b3-5bbe-b5e2-52e8198270a2"
Path: "/sitecore/templates/Project/cts/Styleguide-Explanatory-Component/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220225T044636Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
