---
ID: "07a3a968-1815-4f45-ac80-6c8b1ccfa56e"
Parent: "903f929c-ab86-4fbe-9a2b-5df776240dda"
Template: "903f929c-ab86-4fbe-9a2b-5df776240dda"
Path: /sitecore/templates/Project/Altudo/Tenant/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220317T033205Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
