---
ID: "c5b49680-c8df-5f95-9eee-1fb70feb0c73"
Parent: "bab9c38e-d9ba-50e0-8193-b845bd571a58"
Template: "bab9c38e-d9ba-50e0-8193-b845bd571a58"
Path: "/sitecore/templates/Project/cts/Styleguide-FieldUsage-Text/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220225T044640Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
