---
ID: "8cafc703-c85c-51f1-9837-3c6c65ec4dab"
Parent: "4e13721b-89c8-5d09-b967-6a63dca84625"
Template: "4e13721b-89c8-5d09-b967-6a63dca84625"
Path: "/sitecore/templates/Project/cts/Styleguide-FieldUsage-ContentList/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220225T044638Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
