---
ID: "9d00ff98-0cf6-5343-bb07-8be55f416b03"
Parent: "9968d617-c11b-5c2c-b076-425096753c93"
Template: "9968d617-c11b-5c2c-b076-425096753c93"
Path: "/sitecore/templates/Project/cts/Styleguide-ContentList-Item-Template/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220225T044636Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
