---
ID: "920006a3-88f0-52f7-a67b-997a546ded94"
Parent: "812c8471-5f06-54c5-b279-cd00187fedcc"
Template: "812c8471-5f06-54c5-b279-cd00187fedcc"
Path: "/sitecore/templates/Project/altudoapp/Styleguide-ComponentParams Rendering Parameters/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220225T122128Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
